const express = require("express")
const router = express.Router()

router.use("/admin",require("./web.logo.router"))
router.use("/admin",require("./menu.router"))
router.use("/admin",require("./submenu.router"))
router.use("/admin",require("./coverphoto.router"))
router.use("/admin",require("./about.router"))
router.use("/admin",require("./strategic.advantages.router"))
router.use("/admin",require("./commercialecosystem"))
router.use("/admin",require("./brand.router"))
router.use("/admin",require("./dining-experiences"))
router.use("/admin",require("./floor-plans"))
router.use("/admin",require("./walkthrough.router"))
router.use("/admin",require("./leisure-experiences.router"))
router.use("/admin",require("./landmark.router"))
router.use("/admin",require("./overview.router"))
router.use("/admin",require("./location-advantages"))
router.use("/admin",require("./projecthighlight.router"))
router.use("/admin",require("./retailbrands.router"))
router.use("/admin",require("./globalfashion.jrouter"))
router.use("/admin",require("./accessorylables.router"))
router.use("/admin",require("./finedining.router"))
router.use("/admin",require("./entertainmentleisure.router"))
router.use("/admin",require("./wellness.router"))
router.use("/admin",require("./events.router"))
router.use("/admin",require("./hospitality.router"))
router.use("/admin",require("./experience.router"))
router.use("/admin",require("./amenities.router"))
router.use("/admin",require("./parking.router"))
router.use("/admin",require("./powerbackup.router"))
router.use("/admin",require("./accessibility.router"))
router.use("/admin",require("./smartfeatures"))
router.use("/admin",require("./ourlegacy.router"))
router.use("/admin",require("./vision&philosophy"))
router.use("/admin",require("./previous.projects.router"))
router.use("/admin",require("./contact.router"))




module.exports= router